config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers
  get 'pages/about'

  get 'pages/Home'

  get 'pages/Contact'
  get 'pages/About'

  resources :vehicles
  resources :ncars
  
  
   match "/about" => "pages#about", :via => [:get]
   match "/contact" => "pages#contact", :via => [:get]
  

  root 'vehicles#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
    
     has_many :orders, dependent: :destroy
    
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :customer
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base
  
  

  private

    def customer_params
      params.require(:customer).permit(:name, :email, :phnumber, :address)
    end
    
    
    
    
    def destroy
      
      @customer.destroy
      
    end
    
end

app/controllers/ncars_controller.rb
class NcarsController < ApplicationController
    
    def index
    @vehicles = Vehicle.all
  end
    
    def new
        
    end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base

  private

    def order_params
      params.require(:order).permit(:customerid, :customername, :productid)
    end
    
    def create
    @order = @customer.orders.create(order_date: Time.now)
    end
    
     
     
     
    def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end
    
    
    
    
    
    
    
    
    
    
    def show
    
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  
  def about
  end
  
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy,]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end
  
  
  def ncars
    
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:model, :company, :discription, :price, :iamge)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
   
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phnumber %><br>
    <%= f.text_field :phnumber %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Customers</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phnumber</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phnumber %></td>
        <td><%= customer.address %></td>
        <td><%= link_to 'Show', customer %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Sign Up', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Phnumber:</strong>
  <%= @customer.phnumber %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
  
<!doctype html>
<html>
<head>
<title>ZakirMotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
  
  
  
  
  
  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>adage - Free CSS Template by ZyPOP</title>
<link rel="stylesheet" href="temp.css" type="text/css" />
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--
adage, a free CSS web template by ZyPOP (zypopwebtemplates.com/)

Download: http://zypopwebtemplates.com/

License: Creative Commons Attribution
//-->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
</head>
<body>
    
<div id="container" class="width">
  
    <header>

    	<h1><a href="/">Company<span>  ZM Motors</span></a></h1>

    </header>

    <nav>
	<div class="inner-nav">
    		<ul>
        		<li class="start selected"> <%= link_to "Home",  root_path  %></li>
        		<li class="nav"><%= link_to "About",  about_path  %></li>
        	    <li class="nav"><%= link_to "New Cars",  ncars_path  %></li>
         	   	<li class="nav"><%= link_to "Order",  orders_path  %></li>
          	  	<li class="nav"><%= link_to "Users",  customers_path  %></li>
          	 	<li class="end"><%= link_to "Contact Us",  contact_path  %></li>
        	</ul>
	</div>
    </nav>

    <div id="body">

		

		<section id="content">

	    
	<%= yield %>
		    
        </section>
        
        <aside class="sidebar">
	
            <ul>	
               <li>
                    <h4><span>External Sites</span></h4>
                    <ul>
                    <li><a href="http://www.chevrolet.com/">www.Chevrolet.com</a></li>
                    <li><a href="http://www.buick.com/">www.Buick.com</a></li>
                    <li><a href="http://www.gm.com/">www.GM.com</a></li>
                    <li><a href="http://www.gmc.com/">www.Gmc.com</a></li>
                    <li><a href="http://www.cadillac.com/">www.Cadillac.com</a></li>
                    </ul>
                </li>
                
                <li>
                    <h4><span>About us</span></h4>
                    <ul>
                        <li class="text">
                        	<p style="margin: 0;">ZM-Motors is the leading online destination for car shoppers and owners. We offer credible and easy-to-understand information to help 					<a href="#" class="readmore">Read More &raquo;</a></p>
                        </li>
                    </ul>
                </li>
                
                <li>
                	<h4><span>Search site</span></h4>
                    <ul>
                    	<li class="text">
                            <form method="get" class="searchform" action="#" >
                                <p>
                                    <input type="text" size="45" value="" name="s" class="s" />
                                    
                                </p>
                            </form>	
						</li>
					</ul>
                </li>
                
                <li>
                    <h4><span>Helpful Links</span></h4>
                    <ul>
                        <li><a href="http://www.gmc.com/?evar25=gmcom_global_gmc" title="premium templates">GMC.com</a></li>
                        <li><a href="http://www.cadillac.com/?evar25=gmcom_global_cadillac" title="web hosting">cadillac.com</a></li>
                    
                    </ul>
                </li>
                
            </ul>
		
        </aside>
    	<div class="clear"></div>
    </div>
    
    <footer>
        <div class="footer-content">
            <ul>
            	<li><h4>Follow Us</h4></li>
                <li><a href="#">FaceBook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Google+</a></li>
                <li><a href="#">Linkedin </a></li>
                <li><a href="#">Curabitur sit amet tellus</a></li>
            </ul>
            
            <ul>
            	<li><h4>Quick Links</h4></li>
                <li><a href="#">Home</a></li>
                <li><a href="#">About </a></li>
                <li><a href="#">New Cars</a></li>
                <li><a href="#">Contact Us</a></li>
                <li><a href="#">Cras dictum</a></li>
            </ul>
            
            <ul class="endfooter">
                
            	<li><h4>External Sites</h4></li>
                <li><a href="http://www.chevrolet.com/">Chevrolet</a></li>
                <li><a href="http://www.buick.com/">Buick</a></li>
                <li><a href="http://www.gm.com/">GM</a></li>
                <li><a href="http://www.gmc.com/">Gmc</a></li>
                <li><a href="http://www.cadillac.com/">Cadillac</a></li>
            </ul>
            
            <div class="clear"></div>
        </div>
      
        <div class="footer-bottom">
            <p>&copy; 2016 All rights reserved to ZM Motors. <a href="http://zypopwe</p>
         </div>
    </footer>
</div>


</body>
</html>

app/views/ncars/index.html.erb
   
<p id="notice"><%= notice %></p>



<table>




 




 <% @vehicles.each do |vehicle| %>
 
 
 
    <tr></a><td><table> 
    
    
    
    
    <tr>
        
      <td>
          
        <strong>Company:</strong>
          
      </td>  
      <td>
          
    <%= vehicle.company %>
          
      </td> 
      
      </tr>
      
      
      <tr>
        
      <td>
          
        <strong>Model:</strong>
          
      </td>  
      <td>
          
    <%= vehicle.model %>
          
      </td> 
      
      </tr>
      
      
      
      <tr>
      <td>
          
          
          
    <strong>Price:</strong>
     
 
          
          
      </td>  
        
      <td>
          
          
    <%= vehicle.price %>  
          
          
          
      </td>  
        
    </tr>
    
    
    
    <tr>
      <td>
          
          
          
    <strong>Discription:</strong>
     
 
          
          
      </td>  
        
      <td>
          
          
    <%= vehicle.discription %>  
          
          
          
      </td>  
        
    </tr>
    
    
    
    
    
    
    
    
    
    
        
    </tr>
    
    
    
    
    
    
    
    
    
    </table>
    
    
    
    
    
    
    
    
    
    </td> <td><%= image_tag(vehicle.iamge) %></td> 
       
       
       
        
       
       
        
       
     
        
   
    
   <% end %>





</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customerid %><br>
    <%= f.text_field :customerid %>
  </div>
  <div class="field">
    <%= f.label :customername %><br>
    <%= f.text_field :customername %>
  </div>
  <div class="field">
    <%= f.label :productid %><br>
    <%= f.text_field :productid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Orders</h3>

<table>
  <thead>
    <tr>
      <th>Customerid</th>
      <th>Customername</th>
      <th>Productid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customerid %></td>
        <td><%= order.customername %></td>
        <td><%= order.productid %></td>
        <td><%= link_to 'Show', order %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h3>New Order</h3>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customerid:</strong>
  <%= @order.customerid %>
</p>

<p>
  <strong>Customername:</strong>
  <%= @order.customername %>
</p>

<p>
  <strong>Productid:</strong>
  <%= @order.productid %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
<br/>
<br/>

<h2>About Us</h2>

<br/>
<br/>


<p>
    
ZM-Motors is the leading online destination for car shoppers and owners. We offer credible and easy-to-understand information to help consumers research, price and find new and used vehicles and quality service and repair providers.

Through unbiased editorial content, vehicle listings, dealer reviews, side-by-side comparison options, build and price tools, photo galleries and videos, ZM-Motors gives drivers the information they need to make confident decisions.

Launched in June 2015, ZM-Motors is a fasttest growing online car shop.
</p>

app/views/pages/contact.html.erb
<br>

<h3>Contact ZM Motors</h3>
<br>
<h4>Postal Address</h4>
<p>80, zhongguancun east road. Haidian district, Beijing, China</p>
<h4>Information Office </h4>
<table>
<tr><td>Phone</td><td>+8613051358386</td></tr>    
<tr><td>Fax</td><td>+8613051358386</td></tr>
<tr><td>Email</td><td>zakirullah98@gmail.com</td></tr>
<br>
</table>

<h4>ZM Motors Location</h4>

<iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0"width="550" height="440" src="https://maps.google.com/maps?hl=en&q=Zhongguancun, Haidian, Beijing China&ie=UTF8&t=roadmap&z=10&iwloc=B&output=embed"><div><small><a href="http://embedgooglemaps.com">
									embedgooglemaps.com
							</a></small></div><div><small><a href="https:/www.googlemapsgenerator.com/">generate Google Maps</a></small></div></iframe>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_field :discription %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :iamge %><br>
    <%= f.text_field :iamge %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/file _foo.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>40</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="styles.css" type="text/css" />
</head>
<body>
<h1>Horizontal CSS Navigation Menu</h1>
<hr />
<div id="stylefive">
  <ul>
    <li><a href="http://www.free-css.com/" class="current">CSS Templates</a></li>
    <li><a href="http://www.free-css.com/">CSS Layouts</a></li>
    <li><a href="http://www.free-css.com/">CSS Books</a></li>
    <li><a href="http://www.free-css.com/">CSS Menus</a></li>
    <li><a href="http://www.free-css.com/">CSS Tutorials</a></li>
    <li><a href="http://www.free-css.com/">CSS Reference</a></li>
    <li><a rel="nofollow" target="_blank" href="http://www.13styles.com" title="13styles.com">13styles</a></li>
  </ul>
</div>
</body>
</html>

app/views/vehicles/ncars.html.erb
   
<p id="notice"><%= notice %></p>



<table>




 




 <% @vehicles.each do |vehicle| %>
 
 
 
    <tr></a><td><table> 
    
    
    
    
    <tr>
       
  
      <td>
          
        <strong>Company:</strong>
        
        
        
  
      </td>  
      <td>
          
    <%= vehicle.company %>
          
      </td> 
      
      </tr>
      
      
      <tr>
        
      <td>
          
        <strong>Model:</strong>
          
      </td>  
      <td>
          
    <%= vehicle.model %>
          
      </td> 
      
      </tr>
      
      
      
      <tr>
      <td>
          
          
          
    <strong>Price:</strong>
     
 
          
          
      </td>  
        
      <td>
          
          
    <%= vehicle.price %>  
          
          
          
      </td>  
        
    </tr>
    
    
    
    <tr>
      <td>
          
          
          
    <strong>Discription:</strong>
     
 
          
          
      </td>  
        
      <td>
          
          
    <%= vehicle.discription %>  
          
          
          
      </td>  
        
    </tr>
    
    
    
    
    
    
    
    
    
    
        
    </tr>
    
    
    
    
    
    
    
    
    
    </table>
    
    
    
    
    
    
    
    
    
    </td> <td><%= image_tag(vehicle.iamge) %></td> 
       
       
      
        
       
       
        
       
     
        
   
    
   <% end %>





</table>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="styles.css" type="text/css" />
</head>
<body 

<h1>Horizontal CSS Navigation Menu</h1>
<hr />
<div id="stylefive">
  <ul>
    <li><a href="http://www.free-css.com/ee-css.cocurrents="current">CSS Templates</a></li>
    <li><a href="http://www.free-css.com/">CSS Layouts</a></li>
    <li><a href="http://www.free-css.com/">CSS Books</a></li>
    <li><a href="http://www.free-css.com/">CSS Menus</a></li>
    <li><a href="http://www.free-css.com/">CSS Tutorials</a></li>
    <li><a href="http://www.free-css.com/">CSS Reference</a></li>
    <li><a rel="nofollow" target="_blank" href="http://www.13styles.com" title="13styles.com">13styles</a></li>
  </ul>
</div>


<table style="width:100%">
  <tr>
      <td>
    
      <p id="notice"><%= notice %></p>

      <p>
      <strong>Model:</strong>
      <%= @vehicle.model %>
      </p>

      <p>
      <strong>Company:</strong>
      <%= @vehicle.company %>
      </p>

      <p>
      <strong>Discription:</strong>
      <%= @vehicle.discription %>
      </p>

      <p>
      <strong>Price:</strong>
      <%= @vehicle.price %>
      </p>

      <p>
      <strong>Iamge:</strong>
      <%= image_tag(@vehicle.iamge) %>
      </p>
    <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
    
 </td>
    
   
 <td>
      <p id="notice"><%= notice %></p>

      <p>
      <strong>Model:</strong>
      <%= @vehicle.model %>
      </p>

      <p>
      <strong>Company:</strong>
      <%= @vehicle.company %>
      </p>

      <p>
      <strong>Discription:</strong>
      <%= @vehicle.discription %>
      </p>

      <p>
      <strong>Price:</strong>
      <%= @vehicle.price %>
     </p>

      <p>
     <strong>Iamge:</strong>
     <%= image_tag(@vehicle.iamge) %>
     
     </p>
    <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
 </td> 
   
   
 <td>
    
    
     <p id="notice"><%= notice %></p>

     <p>
     <strong>Model:</strong>
     <%= @vehicle.model %>
     </p>

     <p>
     <strong>Company:</strong>
     <%= @vehicle.company %>
     </p>

     <p>
     <strong>Discription:</strong>
     <%= @vehicle.discription %>
     </p>

     <p>
     <strong>Price:</strong>
     <%= @vehicle.price %>
    </p>

    <p>
    <strong>Iamge:</strong>
    <%= @vehicle.iamge %>
    </p>
    
    
   <%= image_tag(@vehicle.iamge) %>
   <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
</td> </tr>
  
  
  
  
  <tr>
    <td>Eve</td>
    <td>Jackson</td> 
    <td>94</td>
  </tr>
</table>
</body>
</html>
<h1>New Vehicle</h1>


<%= link_to 'new', new_vehicle_path(@vehicle) %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="styles.css" type="text/css" />
</head>
<body 

<h1>Horizontal CSS Navigation Menu</h1>
<hr />
<div id="stylefive">
  <ul>
    <li><a href="http://www.free-css.com/ee-css.cocurrents="current">CSS Templates</a></li>
    <li><a href="http://www.free-css.com/">CSS Layouts</a></li>
    <li><a href="http://www.free-css.com/">CSS Books</a></li>
    <li><a href="http://www.free-css.com/">CSS Menus</a></li>
    <li><a href="http://www.free-css.com/">CSS Tutorials</a></li>
    <li><a href="http://www.free-css.com/">CSS Reference</a></li>
    <li><a rel="nofollow" target="_blank" href="http://www.13styles.com" title="13styles.com">13styles</a></li>
  </ul>
</div>


<table style="width:100%">
  <tr>
      <td>
    
      <p id="notice"><%= notice %></p>

      <p>
      <strong>Model:</strong>
      <%= @vehicle.model %>
      </p>

      <p>
      <strong>Company:</strong>
      <%= @vehicle.company %>
      </p>

      <p>
      <strong>Discription:</strong>
      <%= @vehicle.discription %>
      </p>

      <p>
      <strong>Price:</strong>
      <%= @vehicle.price %>
      </p>

      <p>
      <strong>Iamge:</strong>
      <%= image_tag(@vehicle.iamge) %>
      </p>
    <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
    
 </td>
    
   
 <td>
      <p id="notice"><%= notice %></p>

      <p>
      <strong>Model:</strong>
      <%= @vehicle.model %>
      </p>

      <p>
      <strong>Company:</strong>
      <%= @vehicle.company %>
      </p>

      <p>
      <strong>Discription:</strong>
      <%= @vehicle.discription %>
      </p>

      <p>
      <strong>Price:</strong>
      <%= @vehicle.price %>
     </p>

      <p>
     <strong>Iamge:</strong>
     <%= image_tag(@vehicle.iamge) %>
     
     </p>
    <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
 </td> 
   
   
 <td>
    
    
     <p id="notice"><%= notice %></p>

     <p>
     <strong>Model:</strong>
     <%= @vehicle.model %>
     </p>

     <p>
     <strong>Company:</strong>
     <%= @vehicle.company %>
     </p>

     <p>
     <strong>Discription:</strong>
     <%= @vehicle.discription %>
     </p>

     <p>
     <strong>Price:</strong>
     <%= @vehicle.price %>
    </p>

    <p>
    <strong>Iamge:</strong>
    <%= @vehicle.iamge %>
    </p>
    
    
   <%= image_tag(@vehicle.iamge) %>
   <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>


</td> </tr>
  
  
  
  
  <tr>
    <td>Eve</td>
    <td>Jackson</td> 
    <td>94</td>
  </tr>
</table>
</body>
</html>
<h1>New Vehicle</h1>


<%= link_to 'new', new_vehicle_path(@vehicle) %>



<%= link_to 'edit', edit_vehicle_path(@vehicle) %>